In [2]:
import tensorflow as tf

In [3]:
a = tf.placeholder(tf.float32, shape=[3])
b = tf.constant([5,5,5], tf.float32)

c = a + b

In [4]:
with tf.Session() as sess:
    print(sess.run(c, {a:[1,2,3]}))

[ 6.  7.  8.]


In [5]:
a = tf.add(2,5)
b = tf.multiply(a, 3)

In [6]:
with tf.Session() as sess:
    replace_dict = {a:15}
    
    print(sess.run(b, feed_dict=replace_dict))

45


In [7]:
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')
z = tf.add(x, y)

In [8]:
with tf.Session() as sess:
	sess.run(tf.global_variables_initializer())
	writer = tf.summary.FileWriter('./graphs/l2', sess.graph)
	for _ in range(10):
		sess.run(z)
	print(tf.get_default_graph().as_graph_def())
	writer.close()

node {
  name: "Placeholder"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 3
        }
      }
    }
  }
}
node {
  name: "Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 3
          }
        }
        tensor_content: "\000\000\240@\000\000\240@\000\000\240@"
      }
    }
  }
}
node {
  name: "add"
  op: "Add"
  input: "Placeholder"
  input: "Const"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "Add/x"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 2
      }
    }
  }
}
node {
  name: "Add/y"


In [9]:
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')

with tf.Session() as sess:
	sess.run(tf.global_variables_initializer())
	writer = tf.summary.FileWriter('./graphs/l2', sess.graph)
	for _ in range(10):
		sess.run(tf.add(x, y))
	print(tf.get_default_graph().as_graph_def()) 
	writer.close()

node {
  name: "Placeholder"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 3
        }
      }
    }
  }
}
node {
  name: "Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 3
          }
        }
        tensor_content: "\000\000\240@\000\000\240@\000\000\240@"
      }
    }
  }
}
node {
  name: "add"
  op: "Add"
  input: "Placeholder"
  input: "Const"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "Add/x"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 2
      }
    }
  }
}
node {
  name: "Add/y"


In [10]:
W = tf.Variable(10)
assign_op = W.assign(100)

with tf.Session() as sess:
	sess.run(W.initializer)
	print(W.eval()) # >> 10
	print(sess.run(assign_op)) # >> 100

10
100


In [11]:
my_var = tf.Variable(2, name="my_var") 

# assign 2 * my_var to my_var and run the op my_var_times_two
my_var_times_two = my_var.assign(2 * my_var)

with tf.Session() as sess:
	sess.run(tf.global_variables_initializer())
	print(sess.run(my_var_times_two)) # >> 4
	print(sess.run(my_var_times_two)) # >> 8
	print(sess.run(my_var_times_two)) # >> 16

4
8
16


In [15]:
W = tf.Variable(10)
sess1 = tf.Session()
sess2 = tf.Session()

# You have to initialize W at each session
sess1.run(tf.global_variables_initializer())
sess2.run(W.initializer)

print(sess1.run(W.assign_add(10))) # >> 20
print(sess2.run(W.assign_sub(2))) # >> 8

print(sess1.run(W.assign_add(100))) # >> 120
print(sess2.run(W.assign_sub(50))) # >> -42

sess1.close()
sess2.close()

20
8
120
-42


In [20]:
y = tf.zeros_like([200, 3], optimize=True)
print(y)
with tf.Session() as sess:
    y = sess.run(y)
    print(y)

Tensor("zeros_like_3:0", shape=(2,), dtype=int32)
[0 0]


In [27]:
import numpy as np

with tf.Session() as sess:
	print(sess.run(tf.linspace(10.0, 13.0, 4)))
	print(sess.run(tf.range(10, 14)))
	for i in np.arange(10, 14):
		print(i)

[ 10.  11.  12.  13.]
[10 11 12 13]
10
11
12
13


In [32]:
with tf.device('/gpu:2'):
    a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], name='a')
    b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], name='b')
    c = a * b
    
    sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
    
    print(sess.run(c))

InvalidArgumentError: Cannot assign a device for operation 'mul_1': Operation was explicitly assigned to /device:GPU:2 but available devices are [ /job:localhost/replica:0/task:0/cpu:0 ]. Make sure the device specification refers to a valid device.
	 [[Node: mul_1 = Mul[T=DT_FLOAT, _device="/device:GPU:2"](a_4, b_4)]]

Caused by op u'mul_1', defined at:
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "/usr/local/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/usr/local/lib/python2.7/site-packages/tornado/ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python2.7/site-packages/ipykernel/zmqshell.py", line 501, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-32-a255a3f6bec3>", line 4, in <module>
    c = a * b
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 838, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 1061, in _mul_dispatch
    return gen_math_ops._mul(x, y, name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1377, in _mul
    result = _op_def_lib.apply_op("Mul", x=x, y=y, name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'mul_1': Operation was explicitly assigned to /device:GPU:2 but available devices are [ /job:localhost/replica:0/task:0/cpu:0 ]. Make sure the device specification refers to a valid device.
	 [[Node: mul_1 = Mul[T=DT_FLOAT, _device="/device:GPU:2"](a_4, b_4)]]


In [17]:
import tensorflow as tf

a = tf.constant([[0, 1], [2, 3]], shape=[2,2], dtype=tf.int32 ,name='InputA')
b = tf.constant([[0, 1], [2, 3]], shape=[2,2], dtype=tf.int32,  name='InputB')
x = tf.matmul(a, b, name='SumThisStuff')
z = tf.ones([2, 30], tf.int32)
z1 = tf.zeros_like(z)
z2 = tf.linspace(10.0, 12.0, 1, name="linspace") 
with tf.Session() as sess:
   # writer = tf.summary.FileWriter('graphs', sess.graph)
    print(sess.run(z))
    print(sess.run(z2))
writer.close()

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
[ 10.]


In [23]:
""" Simple logistic regression model to solve OCR task 
with MNIST in TensorFlow
MNIST dataset: yann.lecun.com/exdb/mnist/
Author: Chip Huyen
Prepared for the class CS 20SI: "TensorFlow for Deep Learning Research"
cs20si.stanford.edu
"""
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

import numpy as np
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
import time

# Define paramaters for the model
learning_rate = 0.01
batch_size = 128
n_epochs = 30

# Step 1: Read in data
# using TF Learn's built in function to load MNIST data to the folder data/mnist
mnist = input_data.read_data_sets('mnist', one_hot=True)

Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting mnist/train-images-idx3-ubyte.gz


Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting mnist/train-labels-idx1-ubyte.gz


Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting mnist/t10k-images-idx3-ubyte.gz


Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting mnist/t10k-labels-idx1-ubyte.gz


In [24]:
# Step 2: create placeholders for features and labels
# each image in the MNIST data is of shape 28*28 = 784
# therefore, each image is represented with a 1x784 tensor
# there are 10 classes for each image, corresponding to digits 0 - 9. 
# each lable is one hot vector.
X = tf.placeholder(tf.float32, [batch_size, 784], name='X_placeholder') 
Y = tf.placeholder(tf.int32, [batch_size, 10], name='Y_placeholder')

# Step 3: create weights and bias
# w is initialized to random variables with mean of 0, stddev of 0.01
# b is initialized to 0
# shape of w depends on the dimension of X and Y so that Y = tf.matmul(X, w)
# shape of b depends on Y
w = tf.Variable(tf.random_normal(shape=[784, 10], stddev=0.01), name='weights')
b = tf.Variable(tf.zeros([1, 10]), name="bias")

# Step 4: build model
# the model that returns the logits.
# this logits will be later passed through softmax layer
logits = tf.matmul(X, w) + b 

# Step 5: define loss function
# use cross entropy of softmax of logits as the loss function
entropy = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=Y, name='loss')
loss = tf.reduce_mean(entropy) # computes the mean over all the examples in the batch

# Step 6: define training op
# using gradient descent with learning rate of 0.01 to minimize loss
optimizer = tf.train.AdamOptimizer(learning_rate).minimize(loss)

In [25]:
with tf.Session() as sess:
	# to visualize using TensorBoard
	writer = tf.summary.FileWriter('mnist/graphs/logistic_reg', sess.graph)

	start_time = time.time()
	sess.run(tf.global_variables_initializer())	
	n_batches = int(mnist.train.num_examples/batch_size)
	for i in range(n_epochs): # train the model n_epochs times
		total_loss = 0

		for _ in range(n_batches):
			X_batch, Y_batch = mnist.train.next_batch(batch_size)
			_, loss_batch = sess.run([optimizer, loss], feed_dict={X: X_batch, Y:Y_batch}) 
			total_loss += loss_batch
		print('Average loss epoch {0}: {1}'.format(i, total_loss/n_batches))

	print('Total time: {0} seconds'.format(time.time() - start_time))

	print('Optimization Finished!') # should be around 0.35 after 25 epochs

	# test the model
	
	preds = tf.nn.softmax(logits)
	correct_preds = tf.equal(tf.argmax(preds, 1), tf.argmax(Y, 1))
	accuracy = tf.reduce_sum(tf.cast(correct_preds, tf.float32)) # need numpy.count_nonzero(boolarr) :(
	
	n_batches = int(mnist.test.num_examples/batch_size)
	total_correct_preds = 0
	
	for i in range(n_batches):
		X_batch, Y_batch = mnist.test.next_batch(batch_size)
		accuracy_batch = sess.run([accuracy], feed_dict={X: X_batch, Y:Y_batch}) 
		total_correct_preds += accuracy_batch	
	
	print('Accuracy {0}'.format(total_correct_preds/mnist.test.num_examples))

	writer.close()

Average loss epoch 0: 0.368925113882


Average loss epoch 1: 0.296004552941


Average loss epoch 2: 0.285065905962


Average loss epoch 3: 0.278323887372


Average loss epoch 4: 0.272531557125


Average loss epoch 5: 0.274326382122


Average loss epoch 6: 0.267232034364


Average loss epoch 7: 0.267660491603


Average loss epoch 8: 0.264160065002


Average loss epoch 9: 0.26686498099


Average loss epoch 10: 0.265959430651


Average loss epoch 11: 0.261297412599


Average loss epoch 12: 0.262329736894


Average loss epoch 13: 0.261381448201


Average loss epoch 14: 0.258157572633


Average loss epoch 15: 0.259896231507


Average loss epoch 16: 0.26062720711


Average loss epoch 17: 0.258887436441


Average loss epoch 18: 0.257863994054


Average loss epoch 19: 0.257250513317


Average loss epoch 20: 0.254573019686


Average loss epoch 21: 0.255535919853


Average loss epoch 22: 0.256477896315


Average loss epoch 23: 0.25485866456


Average loss epoch 24: 0.254356767869


Average loss epoch 25: 0.251817209251


Average loss epoch 26: 0.252699480016


Average loss epoch 27: 0.254178118369


Average loss epoch 28: 0.254197322978


Average loss epoch 29: 0.250872513857
Total time: 15.6594829559 seconds
Optimization Finished!


TypeError: unsupported operand type(s) for +=: 'int' and 'list'

In [7]:
import pandas as pd

csv_dataset = pd.DataFrame.from_csv("dataset_middle.csv", index_col="agent_id")

In [13]:
agent_id = csv_dataset.index.tolist()
agent_id

['56654868cc6da11d6e8b4632',
 '54b3dbd6e76da1b0848b4616',
 '5691084d096ea1347b8b45a9',
 '5834232ec66c844d8c37ca7e',
 '54b3da24e56da1cb598b457f',
 '569106ca096ea1ae788b45f0',
 '5691068a096ea1ae788b45e2',
 '54b3da24e56da1cb598b457f',
 '5691084d096ea1347b8b45a9',
 '56654943cd6da1fa8d8b45a7',
 '58342361f1a12c63d05b4e58',
 '5665490de66da1cf978b456b',
 '5834223f348715172b606f88',
 '5834223f348715172b606f88',
 '54b3da24e56da1cb598b457f',
 '54b3d8dde56da1924e8b461e',
 '56654943cd6da1fa8d8b45a7',
 '5691080f096ea1c27b8b4581',
 '5691084d096ea1347b8b45a9',
 '54b3d8dde56da1924e8b461e',
 '566548abe56da1a9508b456a',
 '5834232ec66c844d8c37ca7e',
 '5665497acc6da1e0708b4604',
 '5834223f348715172b606f88',
 '54b3dbd6e76da1b0848b4616',
 '569107d3e66da141608b45ea',
 '54b3dbd6e76da1b0848b4616',
 '569106ca096ea1ae788b45f0',
 '56654868cc6da11d6e8b4632',
 '54b3db87cc6da132198b4598',
 '5834232ec66c844d8c37ca7e',
 '56654a3be56da1aa508b45a3',
 '5665497acc6da1e0708b4604',
 '5691080f096ea1c27b8b4581',
 '56910773e76d