In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
%matplotlib inline

from crowdnet_input import input_dataset

In [7]:
iterator_init_op, next_batch = input_dataset(1, 10, 128, "crowdnet_test")

sess = tf.Session()

sess.run([tf.global_variables_initializer(), tf.local_variables_initializer()])

for _ in range(5):
    sess.run(iterator_init_op)
    for _ in range(10):
        print(sess.run(next_batch))

INFO:crowdenet-input:Produce input for test/validation


INFO:crowdenet-input:train samples in total: 20135


INFO:crowdenet-input:test samples in total: 186


INFO:crowdenet-input:validation samples in total: 2301


INFO:crowdenet-input:Produce shuffled batch with 128 batch size


(array([[[[-0.36248317, -0.36248317, -0.36248317],
         [-0.36248317, -0.36248317, -0.36248317],
         [-0.36248317, -0.36248317, -0.36248317],
         ..., 
         [-0.36248317, -0.36248317, -0.36248317],
         [-0.36248317, -0.36248317, -0.36248317],
         [-0.36248317, -0.36248317, -0.36248317]],

        [[-0.36248317, -0.36248317, -0.36248317],
         [-0.36248317, -0.36248317, -0.36248317],
         [-0.36248317, -0.36248317, -0.36248317],
         ..., 
         [-0.36248317, -0.36248317, -0.36248317],
         [-0.36248317, -0.36248317, -0.36248317],
         [-0.36248317, -0.36248317, -0.36248317]],

        [[-0.36248317, -0.36248317, -0.36248317],
         [-0.36248317, -0.36248317, -0.36248317],
         [-0.36248317, -0.36248317, -0.36248317],
         ..., 
         [-0.36248317, -0.36248317, -0.36248317],
         [-0.36248317, -0.36248317, -0.36248317],
         [-0.36248317, -0.36248317, -0.36248317]],

        ..., 
        [[-0.36248317, -0.36248317

(array([[[[ 1.3806504 ,  1.49314582,  1.41814888],
         [ 1.3806504 ,  1.51189482,  1.3806504 ],
         [ 1.36190116,  1.51189482,  1.39939964],
         ..., 
         [-2.96917415, -2.70668483, -3.02542186],
         [-2.91292644, -2.65043712, -2.96917415],
         [-2.57544017, -2.31295061, -2.63168788]],

        [[ 1.30565345,  1.47439659,  1.3806504 ],
         [ 1.32440269,  1.49314582,  1.39939964],
         [ 1.34315193,  1.51189482,  1.3806504 ],
         ..., 
         [-2.12545824, -1.86296892, -2.14420748],
         [-2.03171206, -1.76922274, -2.05046129],
         [-1.78797197, -1.52548254, -1.80672121]],

        [[ 1.30565345,  1.47439659,  1.3806504 ],
         [ 1.30565345,  1.47439659,  1.3806504 ],
         [ 1.32440269,  1.51189482,  1.36190116],
         ..., 
         [-0.98175436, -0.75676346, -1.0192529 ],
         [-0.96300513, -0.73801422, -1.00050366],
         [-0.94425589, -0.71926498, -0.98175436]],

        ..., 
        [[-0.34428018, -0.28803244

(array([[[[-0.45866385, -0.45866385, -0.45866385],
         [-0.44150904, -0.44150904, -0.44150904],
         [-0.49297354, -0.49297354, -0.49297354],
         ..., 
         [-0.56159288, -0.56159288, -0.56159288],
         [-0.68167669, -0.68167669, -0.68167669],
         [-0.78460568, -0.78460568, -0.78460568]],

        [[-0.45866385, -0.45866385, -0.45866385],
         [-0.68167669, -0.68167669, -0.68167669],
         [-0.49297354, -0.49297354, -0.49297354],
         ..., 
         [-0.3728897 , -0.3728897 , -0.3728897 ],
         [-0.35573485, -0.35573485, -0.35573485],
         [-0.3728897 , -0.3728897 , -0.3728897 ]],

        [[-0.64736706, -0.64736706, -0.64736706],
         [-0.69883156, -0.69883156, -0.69883156],
         [-0.57874769, -0.57874769, -0.57874769],
         ..., 
         [-0.40719935, -0.40719935, -0.40719935],
         [-0.35573485, -0.35573485, -0.35573485],
         [-0.33858001, -0.33858001, -0.33858001]],

        ..., 
        [[-0.63021219, -0.63021219

(array([[[[ 0.34019426, -0.20634419,  0.03128123],
         [ 0.34019426, -0.20634419,  0.03128123],
         [ 0.31643173, -0.23010673,  0.00751868],
         ..., 
         [ 0.81544524,  0.03128123,  0.29266918],
         [ 0.81544524,  0.00751868,  0.34019426],
         [ 0.81544524,  0.03128123,  0.29266918]],

        [[ 0.2451441 , -0.30139434, -0.06376894],
         [ 0.2451441 , -0.30139434, -0.06376894],
         [ 0.26890665, -0.27763182, -0.0400064 ],
         ..., 
         [ 0.76792002, -0.0400064 ,  0.29266918],
         [ 0.76792002, -0.0400064 ,  0.29266918],
         [ 0.74415749, -0.06376894,  0.26890665]],

        [[ 0.10256885, -0.39644471, -0.18258165],
         [ 0.12633139, -0.37268215, -0.15881911],
         [ 0.15009393, -0.34891945, -0.13505657],
         ..., 
         [ 0.76792002, -0.0400064 ,  0.29266918],
         [ 0.74415749, -0.06376894,  0.26890665],
         [ 0.72039491, -0.08753148,  0.2451441 ]],

        ..., 
        [[-0.8954581 , -1.03803337

(array([[[[-0.03137521, -0.03137521, -0.03137521],
         [-0.00735639, -0.00735639, -0.00735639],
         [-0.22352582, -0.22352582, -0.22352582],
         ..., 
         [-1.78474975, -1.78474975, -1.78474975],
         [-1.76073098, -1.76073098, -1.76073098],
         [-1.7367121 , -1.7367121 , -1.7367121 ]],

        [[ 0.30488837,  0.30488837,  0.30488837],
         [ 0.01666244,  0.01666244,  0.01666244],
         [ 0.23283188,  0.23283188,  0.23283188],
         ..., 
         [-1.66465569, -1.66465569, -1.66465569],
         [-1.61661804, -1.61661804, -1.61661804],
         [-1.59259915, -1.59259915, -1.59259915]],

        [[ 0.61713314,  0.61713314,  0.61713314],
         [ 0.25685069,  0.25685069,  0.25685069],
         [ 0.59311432,  0.59311432,  0.59311432],
         ..., 
         [-1.52054262, -1.52054262, -1.52054262],
         [-1.49652374, -1.49652374, -1.49652374],
         [-1.49652374, -1.49652374, -1.49652374]],

        ..., 
        [[ 0.56909549,  0.56909549

(array([[[[ -9.84940827e-01,  -1.03693330e+00,  -1.02393520e+00],
         [ -1.03693330e+00,  -1.06292963e+00,  -1.04993153e+00],
         [ -1.01093709e+00,  -1.03693330e+00,  -1.02393520e+00],
         ..., 
         [ -9.45946395e-01,  -9.45946395e-01,  -9.19950128e-01],
         [ -9.45946395e-01,  -9.45946395e-01,  -9.19950128e-01],
         [ -9.45946395e-01,  -9.45946395e-01,  -9.19950128e-01]],

        [[ -9.84940827e-01,  -1.03693330e+00,  -1.02393520e+00],
         [ -1.04993153e+00,  -1.07592773e+00,  -1.06292963e+00],
         [ -1.03693330e+00,  -1.06292963e+00,  -1.04993153e+00],
         ..., 
         [ -9.45946395e-01,  -9.45946395e-01,  -9.19950128e-01],
         [ -9.45946395e-01,  -9.45946395e-01,  -9.19950128e-01],
         [ -9.45946395e-01,  -9.45946395e-01,  -9.19950128e-01]],

        [[ -9.84940827e-01,  -1.03693330e+00,  -1.02393520e+00],
         [ -1.06292963e+00,  -1.08892584e+00,  -1.07592773e+00],
         [ -1.04993153e+00,  -1.07592773e+00,  -1.06292

(array([[[[-0.46283585, -0.55588835, -0.66223413],
         [-0.47612906, -0.52930194, -0.64894092],
         [-0.43624941, -0.52930194, -0.60906124],
         ..., 
         [-0.68882054, -0.70211375, -0.72870022],
         [-0.67552733, -0.68882054, -0.71540695],
         [-0.66223413, -0.67552733, -0.70211375]],

        [[-0.46283585, -0.55588835, -0.66223413],
         [-0.44954264, -0.54259515, -0.64894092],
         [-0.43624941, -0.52930194, -0.63564765],
         ..., 
         [-0.68882054, -0.70211375, -0.72870022],
         [-0.67552733, -0.68882054, -0.71540695],
         [-0.67552733, -0.68882054, -0.71540695]],

        [[-0.44954264, -0.54259515, -0.64894092],
         [-0.44954264, -0.54259515, -0.64894092],
         [-0.43624941, -0.52930194, -0.63564765],
         ..., 
         [-0.70211375, -0.71540695, -0.74199343],
         [-0.68882054, -0.70211375, -0.72870022],
         [-0.67552733, -0.68882054, -0.71540695]],

        ..., 
        [[-0.38307643, -0.50271553

(array([[[[ -2.83572048e-01,  -2.83572048e-01,  -2.83572048e-01],
         [ -2.83572048e-01,  -2.83572048e-01,  -2.83572048e-01],
         [ -2.83572048e-01,  -2.83572048e-01,  -2.83572048e-01],
         ..., 
         [ -2.83572048e-01,  -2.83572048e-01,  -2.83572048e-01],
         [ -2.83572048e-01,  -2.83572048e-01,  -2.83572048e-01],
         [ -2.83572048e-01,  -2.83572048e-01,  -2.83572048e-01]],

        [[ -2.83572048e-01,  -2.83572048e-01,  -2.83572048e-01],
         [ -2.83572048e-01,  -2.83572048e-01,  -2.83572048e-01],
         [ -2.83572048e-01,  -2.83572048e-01,  -2.83572048e-01],
         ..., 
         [ -2.83572048e-01,  -2.83572048e-01,  -2.83572048e-01],
         [ -2.83572048e-01,  -2.83572048e-01,  -2.83572048e-01],
         [ -2.83572048e-01,  -2.83572048e-01,  -2.83572048e-01]],

        [[ -2.83572048e-01,  -2.83572048e-01,  -2.83572048e-01],
         [ -2.83572048e-01,  -2.83572048e-01,  -2.83572048e-01],
         [ -2.83572048e-01,  -2.83572048e-01,  -2.83572

(array([[[[-0.42343116,  0.26390538,  0.96421051],
         [-0.43639979,  0.25093678,  0.95124191],
         [-0.44936839,  0.21203093,  0.92530465],
         ..., 
         [-0.70874065, -0.64389759, -0.3585881 ],
         [-0.72170925, -0.64389759, -0.33265087],
         [-0.73467785, -0.63092899, -0.33265087]],

        [[-0.37155673,  0.34171706,  1.04202223],
         [-0.37155673,  0.31577983,  1.01608491],
         [-0.41046256,  0.27687401,  0.97717911],
         ..., 
         [-0.64389759, -0.68280339, -0.43639979],
         [-0.65686619, -0.66983479, -0.43639979],
         [-0.66983479, -0.65686619, -0.42343116]],

        [[-0.29374504,  0.44546595,  1.13280272],
         [-0.30671367,  0.40656012,  1.10686541],
         [-0.3456195 ,  0.36765429,  1.06795955],
         ..., 
         [-0.63092899, -0.70874065, -0.52718008],
         [-0.60499173, -0.69577205, -0.48827422],
         [-0.63092899, -0.68280339, -0.48827422]],

        ..., 
        [[ 1.82013917,  1.79420185

(array([[[[ 2.62393856,  3.06575298,  2.8247633 ],
         [ 2.66410351,  3.02558804,  2.8247633 ],
         [ 2.86492825,  3.30674338,  3.06575298],
         ..., 
         [ 0.41486654,  0.93701088,  1.25833046],
         [ 0.37470159,  0.97717583,  1.25833046],
         [ 0.21404181,  0.93701088,  1.09767067]],

        [[ 2.78459835,  3.22641349,  2.98542309],
         [ 2.62393856,  3.06575298,  2.8247633 ],
         [ 2.7444334 ,  3.18624854,  2.94525814],
         ..., 
         [ 0.49519643,  1.01734078,  1.33866036],
         [ 0.49519643,  1.09767067,  1.37882531],
         [ 0.25420675,  0.97717583,  1.13783562]],

        [[ 2.86492825,  3.38707328,  3.10591793],
         [ 2.50344372,  3.02558804,  2.7444334 ],
         [ 2.58377361,  3.10591793,  2.8247633 ],
         ..., 
         [ 0.45503148,  1.05750573,  1.33866036],
         [ 0.49519643,  1.09767067,  1.37882531],
         [ 0.37470159,  1.09767067,  1.25833046]],

        ..., 
        [[-1.07123685,  0.01321708

(array([[[[ 1.26135457,  1.09654558,  0.86993289],
         [ 1.28195572,  1.11714673,  0.89053434],
         [ 1.28195572,  1.11714673,  0.89053434],
         ..., 
         [-0.28373009, -0.67515141, -0.98416823],
         [-0.44853908, -0.88116264, -1.23138189],
         [-0.73695475, -1.16957855, -1.60220206]],

        [[ 1.24075341,  1.07594442,  0.84933174],
         [ 1.24075341,  1.07594442,  0.84933174],
         [ 1.26135457,  1.09654558,  0.86993289],
         ..., 
         [ 0.725725  ,  0.35490474,  0.06648902],
         [ 0.62271935,  0.23129801, -0.07771885],
         [ 0.43730924,  0.06648902, -0.34553346]],

        [[ 1.24075341,  1.07594442,  0.84933174],
         [ 1.24075341,  1.07594442,  0.84933174],
         [ 1.24075341,  1.07594442,  0.84933174],
         ..., 
         [ 1.22015226,  0.89053434,  0.62271935],
         [ 1.17895007,  0.80812949,  0.51971376],
         [ 1.15834892,  0.80812949,  0.47851148]],

        ..., 
        [[-1.02537048, -1.43739307

(array([[[[ -2.84472406e-01,  -3.72355610e-01,  -5.70092857e-01],
         [ -3.72355610e-01,  -4.38268036e-01,  -6.36005282e-01],
         [ -4.16297227e-01,  -4.82209653e-01,  -6.79946899e-01],
         ..., 
         [  6.38301611e-01,   6.70606643e-02,  -2.18559816e-01],
         [  6.60272419e-01,   8.90314728e-02,  -1.96589008e-01],
         [  7.26184845e-01,   1.54943883e-01,  -1.74618199e-01]],

        [[ -3.50384802e-01,  -4.16297227e-01,  -6.14034474e-01],
         [ -3.72355610e-01,  -4.38268036e-01,  -6.36005282e-01],
         [ -4.60238844e-01,  -5.26151240e-01,  -7.23888516e-01],
         ..., 
         [  8.14068079e-01,   1.98885500e-01,  -6.47641718e-02],
         [  7.92097270e-01,   1.76914692e-01,  -1.30676582e-01],
         [  7.70126462e-01,   1.54943883e-01,  -1.52647391e-01]],

        [[ -3.72355610e-01,  -4.38268036e-01,  -6.36005282e-01],
         [ -3.72355610e-01,  -4.38268036e-01,  -5.92063665e-01],
         [ -5.26151240e-01,  -5.26151240e-01,  -7.01917

(array([[[[ -8.90459895e-01,  -7.48490751e-01,  -8.51741016e-01],
         [ -8.64647269e-01,  -7.09771872e-01,  -8.38834703e-01],
         [ -8.64647269e-01,  -6.96865618e-01,  -8.25928450e-01],
         ..., 
         [  6.19575799e-01,   1.80762038e-01,  -3.09676886e-01],
         [  6.58294857e-01,   2.45293468e-01,  -2.83864319e-01],
         [  6.58294857e-01,   2.58199751e-01,  -3.09676886e-01]],

        [[ -9.03366148e-01,  -7.48490751e-01,  -8.77553582e-01],
         [ -8.64647269e-01,  -7.09771872e-01,  -8.64647269e-01],
         [ -8.51741016e-01,  -6.71053052e-01,  -8.38834703e-01],
         ..., 
         [  6.71201110e-01,   2.32387170e-01,  -2.58051753e-01],
         [  6.45388544e-01,   2.32387170e-01,  -2.96770602e-01],
         [  6.45388544e-01,   2.45293468e-01,  -3.22583169e-01]],

        [[ -9.16272461e-01,  -7.61397064e-01,  -9.16272461e-01],
         [ -8.64647269e-01,  -7.09771872e-01,  -8.90459895e-01],
         [ -8.38834703e-01,  -6.58146739e-01,  -8.51741

(array([[[[ -7.88684726e-01,  -6.87240779e-01,  -1.32971787e+00],
         [ -5.85797012e-01,  -5.51982462e-01,  -1.16064501e+00],
         [ -7.54870176e-01,  -7.21055329e-01,  -1.32971787e+00],
         ..., 
         [ -1.39734709e+00,  -1.26208878e+00,  -1.76930737e+00],
         [ -1.16064501e+00,  -1.02538681e+00,  -1.60023451e+00],
         [ -8.22499335e-01,  -7.88684726e-01,  -1.39734709e+00]],

        [[ -7.54870176e-01,  -6.53426170e-01,  -1.29590333e+00],
         [ -6.19611621e-01,  -5.85797012e-01,  -1.19445968e+00],
         [ -8.56313884e-01,  -8.22499335e-01,  -1.43116164e+00],
         ..., 
         [ -9.91572201e-01,  -8.56313884e-01,  -1.36353254e+00],
         [ -9.57757592e-01,  -8.22499335e-01,  -1.39734709e+00],
         [ -8.90128434e-01,  -8.56313884e-01,  -1.46497619e+00]],

        [[ -6.53426170e-01,  -6.19611621e-01,  -1.22827423e+00],
         [ -5.85797012e-01,  -5.51982462e-01,  -1.16064501e+00],
         [ -7.54870176e-01,  -7.21055329e-01,  -1.32971

(array([[[[  1.10009134e+00,   1.41362083e+00,   1.82362092e+00],
         [  8.58914614e-01,   1.22067952e+00,   1.67891502e+00],
         [  3.39126873e+00,   3.82538652e+00,   4.30773973e+00],
         ..., 
         [  1.11267343e-01,   2.80090898e-01,   5.21267474e-01],
         [  1.11267343e-01,   2.80090898e-01,   5.21267474e-01],
         [  1.83620304e-01,   3.52443874e-01,   5.93620420e-01]],

        [[  9.79502857e-01,   1.26891482e+00,   1.65479732e+00],
         [  4.48914498e-01,   7.62443960e-01,   1.17244422e+00],
         [  3.51185703e+00,   3.92185712e+00,   4.40421009e+00],
         ..., 
         [  2.07737952e-01,   4.00679171e-01,   6.65973365e-01],
         [  1.11267343e-01,   2.55973250e-01,   5.45385122e-01],
         [  6.30320311e-02,   2.07737952e-01,   4.97149795e-01]],

        [[  9.79502857e-01,   1.19656193e+00,   1.55832672e+00],
         [  7.14208663e-01,   1.00362074e+00,   1.38950312e+00],
         [  3.60832763e+00,   3.92185712e+00,   4.38009

(array([[[[  1.57208240e+00,   1.48646057e+00,   1.34732497e+00],
         [  1.65770423e+00,   1.59348786e+00,   1.46505511e+00],
         [  1.62559605e+00,   1.53997421e+00,   1.42224407e+00],
         ..., 
         [  1.78613710e+00,   1.78613710e+00,   1.65770423e+00],
         [  1.82894802e+00,   1.80754256e+00,   1.66840696e+00],
         [  1.61489332e+00,   1.55067694e+00,   1.37943316e+00]],

        [[  1.63629878e+00,   1.55067694e+00,   1.41154134e+00],
         [  1.72192073e+00,   1.65770423e+00,   1.52927148e+00],
         [  1.61489332e+00,   1.52927148e+00,   1.41154134e+00],
         ..., 
         [  1.75402892e+00,   1.75402892e+00,   1.62559605e+00],
         [  1.85035348e+00,   1.80754256e+00,   1.67910981e+00],
         [  1.62559605e+00,   1.55067694e+00,   1.37943316e+00]],

        [[  1.65770423e+00,   1.57208240e+00,   1.43294692e+00],
         [  1.68981254e+00,   1.60419059e+00,   1.46505511e+00],
         [  1.66840696e+00,   1.60419059e+00,   1.45435

(array([[[[ 2.308249  ,  2.36171198,  2.23696589],
         [ 2.34389091,  2.39735365,  2.27260733],
         [ 2.25478673,  2.308249  ,  2.18350339],
         ..., 
         [ 2.53992033,  2.53992033,  2.50427866],
         [ 2.53992033,  2.53992033,  2.50427866],
         [ 2.53992033,  2.53992033,  2.50427866]],

        [[ 2.308249  ,  2.36171198,  2.23696589],
         [ 2.36171198,  2.41517425,  2.29042864],
         [ 2.27260733,  2.32607031,  2.20132422],
         ..., 
         [ 2.53992033,  2.53992033,  2.50427866],
         [ 2.53992033,  2.53992033,  2.50427866],
         [ 2.53992033,  2.53992033,  2.50427866]],

        [[ 2.36171198,  2.41517425,  2.29042864],
         [ 2.36171198,  2.41517425,  2.29042864],
         [ 2.32607031,  2.37953258,  2.25478673],
         ..., 
         [ 2.53992033,  2.53992033,  2.50427866],
         [ 2.53992033,  2.53992033,  2.50427866],
         [ 2.53992033,  2.53992033,  2.50427866]],

        ..., 
        [[-0.02628232, -0.52526605

(array([[[[-0.21170746, -0.64533347, -0.99223435],
         [-0.35046777, -0.78409392, -1.1309948 ],
         [-0.38515785, -0.818784  , -1.16568482],
         ..., 
         [ 1.80031717,  0.96775538,  0.30864385],
         [ 1.74828207,  0.91572022,  0.25660872],
         [ 1.69624698,  0.86368513,  0.20457362]],

        [[-0.28108761, -0.71471375, -1.06161451],
         [-0.38515785, -0.818784  , -1.16568482],
         [-0.38515785, -0.818784  , -1.16568482],
         ..., 
         [ 1.74828207,  0.91572022,  0.25660872],
         [ 1.71359193,  0.88103014,  0.22191866],
         [ 1.66155684,  0.82899505,  0.16988353]],

        [[-0.31577769, -0.74940383, -1.09630466],
         [-0.36781281, -0.80143893, -1.14833975],
         [-0.29843265, -0.73205876, -1.07895958],
         ..., 
         [ 1.730937  ,  0.89837521,  0.2392637 ],
         [ 1.71359193,  0.88103014,  0.22191866],
         [ 1.67890191,  0.84634006,  0.18722858]],

        ..., 
        [[ 1.85235262,  1.730937  

(array([[[[ -1.75813270e+00,  -1.75813270e+00,  -1.19022036e+00],
         [ -1.74142933e+00,  -1.74142933e+00,  -1.17351699e+00],
         [ -1.74142933e+00,  -1.74142933e+00,  -1.17351699e+00],
         ..., 
         [  1.66604495e+00,   1.14824235e+00,   3.63187104e-01],
         [  1.63263845e+00,   1.16494560e+00,   3.63187104e-01],
         [  1.63263845e+00,   1.16494560e+00,   3.63187104e-01]],

        [[ -1.75813270e+00,  -1.75813270e+00,  -1.19022036e+00],
         [ -1.75813270e+00,  -1.75813270e+00,  -1.19022036e+00],
         [ -1.75813270e+00,  -1.75813270e+00,  -1.19022036e+00],
         ..., 
         [  1.66604495e+00,   1.14824235e+00,   3.63187104e-01],
         [  1.66604495e+00,   1.14824235e+00,   3.63187104e-01],
         [  1.63263845e+00,   1.16494560e+00,   3.63187104e-01]],

        [[ -1.75813270e+00,  -1.75813270e+00,  -1.19022036e+00],
         [ -1.75813270e+00,  -1.75813270e+00,  -1.19022036e+00],
         [ -1.75813270e+00,  -1.75813270e+00,  -1.19022

(array([[[[ -3.43372136e-01,  -3.43372136e-01,  -3.43372136e-01],
         [ -3.12669009e-01,  -3.12669009e-01,  -3.12669009e-01],
         [ -2.97317445e-01,  -2.97317445e-01,  -2.97317445e-01],
         ..., 
         [ -1.57149732e+00,  -1.57149732e+00,  -1.57149732e+00],
         [ -1.63290358e+00,  -1.63290358e+00,  -1.63290358e+00],
         [ -1.70966136e+00,  -1.70966136e+00,  -1.70966136e+00]],

        [[ -3.43372136e-01,  -3.43372136e-01,  -3.43372136e-01],
         [ -3.12669009e-01,  -3.12669009e-01,  -3.12669009e-01],
         [ -2.81965882e-01,  -2.81965882e-01,  -2.81965882e-01],
         ..., 
         [ -1.49473953e+00,  -1.49473953e+00,  -1.49473953e+00],
         [ -1.55614579e+00,  -1.55614579e+00,  -1.55614579e+00],
         [ -1.63290358e+00,  -1.63290358e+00,  -1.63290358e+00]],

        [[ -3.58723700e-01,  -3.58723700e-01,  -3.58723700e-01],
         [ -3.12669009e-01,  -3.12669009e-01,  -3.12669009e-01],
         [ -2.81965882e-01,  -2.81965882e-01,  -2.81965

(array([[[[  2.40029812e+00,   2.52015495e+00,   7.07320392e-01],
         [  2.44524431e+00,   2.59506536e+00,   7.52266705e-01],
         [  2.41528010e+00,   2.56510115e+00,   7.37284601e-01],
         ..., 
         [  2.38531590e+00,   2.49019074e+00,   1.06689084e+00],
         [  2.38531590e+00,   2.47520852e+00,   1.15678346e+00],
         [  2.40029812e+00,   2.47520852e+00,   1.27664030e+00]],

        [[  1.39649701e+00,   1.53133595e+00,  -4.17848118e-02],
         [  1.60624647e+00,   1.74108565e+00,   1.38000399e-01],
         [  1.71112120e+00,   1.89090657e+00,   2.72839308e-01],
         ..., 
         [  1.29162228e+00,   1.41147912e+00,   1.67964607e-01],
         [  1.20172977e+00,   1.32158649e+00,   1.67964607e-01],
         [  1.14180136e+00,   1.24667609e+00,   2.27893010e-01]],

        [[  3.02803636e-01,   4.52624649e-01,  -8.35836291e-01],
         [  6.17427766e-01,   7.67248809e-01,  -5.36194265e-01],
         [  7.97212958e-01,   9.47034001e-01,  -3.86373

(array([[[[-0.3321633 , -0.63079739, -0.73034203],
         [-0.35207224, -0.65070629, -0.75025094],
         [-0.35207224, -0.65070629, -0.75025094],
         ..., 
         [ 1.34018683,  1.38000464,  1.16100645],
         [ 1.32027793,  1.36009574,  1.14109755],
         [ 1.57909393,  1.61891174,  1.39991355]],

        [[-0.31225437, -0.61088848, -0.71043307],
         [-0.3321633 , -0.63079739, -0.73034203],
         [-0.35207224, -0.65070629, -0.75025094],
         ..., 
         [ 1.38000464,  1.41982257,  1.20082426],
         [ 1.32027793,  1.36009574,  1.14109755],
         [ 1.49945819,  1.53927612,  1.32027793]],

        [[-0.21270974, -0.51134384, -0.65070629],
         [-0.23261866, -0.59097952, -0.67061526],
         [-0.29234546, -0.65070629, -0.73034203],
         ..., 
         [ 1.47954929,  1.51936722,  1.30036891],
         [ 1.39991355,  1.43973148,  1.22073328],
         [ 1.43973148,  1.47954929,  1.2605511 ]],

        ..., 
        [[-1.30770099, -1.30770099

(array([[[[-0.00333093, -0.19740146, -0.2168085 ],
         [ 0.07429723, -0.13918035, -0.17799442],
         [ 0.13251835, -0.15858738, -0.2168085 ],
         ..., 
         [ 1.54923213,  1.7044884 ,  2.59721255],
         [ 1.62686026,  1.80152392,  2.63602662],
         [ 1.7044884 ,  1.87915206,  2.71365499]],

        [[ 0.09370427, -0.10036612, -0.11977316],
         [ 0.17133242, -0.10036612, -0.15858738],
         [ 0.17133242, -0.11977316, -0.17799442],
         ..., 
         [ 1.45219696,  1.60745323,  2.50017738],
         [ 1.56863916,  1.74330282,  2.57780552],
         [ 1.64626729,  1.82093096,  2.65543365]],

        [[ 0.15192538, -0.042145  , -0.06155204],
         [ 0.2101465 , -0.06155204, -0.11977316],
         [ 0.17133242, -0.11977316, -0.17799442],
         ..., 
         [ 1.37456882,  1.52982509,  2.42254925],
         [ 1.45219696,  1.62686026,  2.46136332],
         [ 1.51041806,  1.68508136,  2.51958442]],

        ..., 
        [[-0.4108789 , -0.5855422 

(array([[[[  9.22647178e-01,   3.66838455e-01,   3.52211922e-01],
         [  8.49514425e-01,   3.22958827e-01,   3.22958827e-01],
         [  7.03249037e-01,   2.64452666e-01,   2.93705761e-01],
         ..., 
         [  1.05428600e+00,  -3.79115283e-01,  -7.74031878e-01],
         [  1.55158842e+00,   1.76693410e-01,  -5.69260299e-01],
         [  2.60469961e+00,   1.25905764e+00,   2.79079199e-01]],

        [[  9.51900244e-01,   3.66838455e-01,   3.37585360e-01],
         [  8.49514425e-01,   3.37585360e-01,   3.08332294e-01],
         [  6.59369409e-01,   2.20573038e-01,   2.49826118e-01],
         ..., 
         [  1.14204526e+00,  -4.66874540e-01,  -6.86272681e-01],
         [  1.69785380e+00,  -2.80781668e-02,  -5.83886862e-01],
         [  2.73633862e+00,   9.37273681e-01,   7.43076280e-02]],

        [[  9.37273681e-01,   3.66838455e-01,   2.93705761e-01],
         [  8.49514425e-01,   2.93705761e-01,   2.49826118e-01],
         [  6.44742846e-01,   2.05946505e-01,   2.05946

(array([[[[-0.8455866 , -0.15771417,  0.50149685],
         [-0.96023196, -0.28669035,  0.37252071],
         [-0.94590127, -0.25802889,  0.40118206],
         ..., 
         [ 2.04920983,  1.36133718,  1.03173172],
         [ 2.09220171,  1.4043293 ,  1.07472384],
         [ 2.10653234,  1.41865993,  1.08905447]],

        [[-0.91723996, -0.24369821,  0.41551283],
         [-0.94590127, -0.25802889,  0.40118206],
         [-0.93157059, -0.24369821,  0.41551283],
         ..., 
         [ 2.09220171,  1.4043293 ,  1.07472384],
         [ 2.1208632 ,  1.43299055,  1.10338509],
         [ 2.13519382,  1.4473213 ,  1.11771584]],

        [[-0.96023196, -0.28669035,  0.37252071],
         [-0.93157059, -0.24369821,  0.41551283],
         [-0.91723996, -0.22936754,  0.42984352],
         ..., 
         [ 2.09220171,  1.4043293 ,  1.07472384],
         [ 2.1208632 ,  1.43299055,  1.10338509],
         [ 2.10653234,  1.41865993,  1.08905447]],

        ..., 
        [[-0.83125591, -0.80259454

(array([[[[ -1.89193857e+00,  -1.71960318e+00,  -1.40626609e+00],
         [ -1.86060488e+00,  -1.68826950e+00,  -1.37493241e+00],
         [ -1.82927120e+00,  -1.65693569e+00,  -1.34359872e+00],
         ..., 
         [  1.31976616e+00,   5.83424032e-01,   1.44752190e-01],
         [  1.30409932e+00,   5.67757189e-01,   1.29085332e-01],
         [  1.28843248e+00,   5.52090347e-01,   8.20847824e-02]],

        [[ -1.89193857e+00,  -1.71960318e+00,  -1.40626609e+00],
         [ -1.86060488e+00,  -1.68826950e+00,  -1.37493241e+00],
         [ -1.81360435e+00,  -1.64126885e+00,  -1.32793188e+00],
         ..., 
         [  1.31976616e+00,   5.83424032e-01,   1.44752190e-01],
         [  1.30409932e+00,   5.67757189e-01,   1.29085332e-01],
         [  1.30409932e+00,   5.67757189e-01,   9.77516323e-02]],

        [[ -1.86060488e+00,  -1.68826950e+00,  -1.37493241e+00],
         [ -1.84493804e+00,  -1.67260265e+00,  -1.35926557e+00],
         [ -1.81360435e+00,  -1.64126885e+00,  -1.32793

(array([[[[  4.88991886e-01,   3.95484656e-01,   6.76006317e-01],
         [  4.88991886e-01,   3.95484656e-01,   6.76006317e-01],
         [  4.57822829e-01,   3.64315599e-01,   6.44837260e-01],
         ..., 
         [  1.14962757e-01,  -7.20516890e-02,   3.01977456e-01],
         [  8.37936848e-02,  -1.03220761e-01,   2.70808369e-01],
         [  1.46131828e-01,  -4.08826135e-02,   3.33146513e-01]],

        [[  4.88991886e-01,   3.95484656e-01,   6.76006317e-01],
         [  4.88991886e-01,   3.95484656e-01,   6.76006317e-01],
         [  4.88991886e-01,   3.95484656e-01,   6.76006317e-01],
         ..., 
         [  8.37936848e-02,  -1.03220761e-01,   2.70808369e-01],
         [  8.37936848e-02,  -1.03220761e-01,   2.70808369e-01],
         [  1.46131828e-01,  -4.08826135e-02,   3.33146513e-01]],

        [[  5.20160973e-01,   4.26653743e-01,   7.07175434e-01],
         [  4.88991886e-01,   3.95484656e-01,   6.76006317e-01],
         [  4.88991886e-01,   3.95484656e-01,   6.76006

(array([[[[  8.58719468e-01,   6.83011532e-01,   3.60880852e-01],
         [  8.58719468e-01,   6.83011532e-01,   3.31596255e-01],
         [  8.29434812e-01,   6.68369234e-01,   2.58384734e-01],
         ..., 
         [  1.31263089e+00,   9.75857854e-01,   5.21946192e-01],
         [  1.29798853e+00,   9.61215556e-01,   5.07303894e-01],
         [  1.23941934e+00,   9.02646363e-01,   4.48734671e-01]],

        [[  9.61215556e-01,   7.41581023e-01,   4.34092373e-01],
         [  9.31930959e-01,   7.12296188e-01,   3.75523150e-01],
         [  8.58719468e-01,   6.24442339e-01,   2.43742421e-01],
         ..., 
         [  1.38584244e+00,   1.04906940e+00,   5.95157743e-01],
         [  1.35655785e+00,   1.01978481e+00,   5.65873146e-01],
         [  1.31263089e+00,   9.75857854e-01,   5.21946192e-01]],

        [[  1.04906940e+00,   8.00150216e-01,   5.07303894e-01],
         [  9.75857854e-01,   7.41581023e-01,   4.04807776e-01],
         [  8.73361766e-01,   6.24442339e-01,   2.43742

(array([[[[-0.16238137,  0.04504613,  0.17269382],
         [-0.09855752,  0.06100209,  0.20460574],
         [-0.05068964,  0.09291402,  0.17269382],
         ..., 
         [ 0.4120335 , -0.43363273, -0.72084004],
         [ 0.39607754, -0.44958869, -0.73679602],
         [ 0.38012156, -0.46554464, -0.75275195]],

        [[ 0.12482594,  0.23651767,  0.33225369],
         [ 0.23651767,  0.31629771,  0.38012156],
         [ 0.28438556,  0.34820965,  0.39607754],
         ..., 
         [ 0.42798945, -0.41767675, -0.70488405],
         [ 0.4120335 , -0.43363273, -0.72084004],
         [ 0.39607754, -0.44958869, -0.73679602]],

        [[ 0.55563712,  0.57159311,  0.60350502],
         [ 0.60350502,  0.60350502,  0.60350502],
         [ 0.65137291,  0.63541698,  0.60350502],
         ..., 
         [ 0.4918133 , -0.40172079, -0.67297214],
         [ 0.47585735, -0.41767675, -0.68892813],
         [ 0.45990139, -0.43363273, -0.70488405]],

        ..., 
        [[ 0.23651767,  0.02909017

KeyboardInterrupt: 

In [24]:
input_images, labels, _ = crowdnet_input.inputs(dataset_type=0, 
                                             batch_size=1, 
                                             num_epochs=100, 
                                             train_dir="crowdnet_test",
                                             with_transformation=True)

INFO:crowdenet-input:Produce input for training


INFO:crowdenet-input:Num epochs for input: 100


INFO:crowdenet-input:Images will be resized to 256 x 256


INFO:crowdenet-input:train samples in total: 20135


INFO:crowdenet-input:test samples in total: 186


INFO:crowdenet-input:validation samples in total: 2301


INFO:crowdenet-input:Produce shuffled batch with 1 batch size


In [20]:
type(input_images)

tensorflow.python.framework.ops.Tensor

In [26]:
# The op for initializing the variables.
init_op = tf.group(tf.global_variables_initializer(),
                   tf.local_variables_initializer())

with tf.Session()  as sess:
    
    sess.run(init_op)
    
    coord = tf.train.Coordinator()
    threads = tf.train.start_queue_runners(coord=coord)
    
    img, lbls = sess.run([input_images, labels])   
       
    type(img)
    
    coord.request_stop()
    coord.join(threads)

NotFoundError: crowndet
	 [[Node: matching_filenames/MatchingFiles = MatchingFiles[_device="/job:localhost/replica:0/task:0/cpu:0"](matching_filenames/MatchingFiles/pattern)]]

Caused by op u'matching_filenames/MatchingFiles', defined at:
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "/usr/local/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/usr/local/lib/python2.7/site-packages/tornado/ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python2.7/site-packages/ipykernel/zmqshell.py", line 501, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2827, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-3dee7eb2227e>", line 4, in <module>
    tf.train.match_filenames_once(os.path.join("crowndet","train-*"))
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 67, in match_filenames_once
    name=name, initial_value=io_ops.matching_files(pattern),
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 152, in matching_files
    Returns:
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    return self._functions.get(name, None)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    status)

NotFoundError (see above for traceback): crowndet
	 [[Node: matching_filenames/MatchingFiles = MatchingFiles[_device="/job:localhost/replica:0/task:0/cpu:0"](matching_filenames/MatchingFiles/pattern)]]


In [11]:
import re, os
c = 0
for fn in ([f for f in os.listdir('crowdnet/') if re.match(r'train-*', f)]):
    for _ in tf.python_io.tf_record_iterator(fn):
        c += 1
print("samples in total: {}".format(c))

NotFoundError: train-00000-of-00002.tfrecords

['test-00000-of-00001.tfrecords',
 'train-00000-of-00002.tfrecords',
 'train-00001-of-00002.tfrecords',
 'validation-00000-of-00001.tfrecords']

In [15]:
[os.path.abspath(os.path.join('crowdnet/', f)) for f in os.listdir('crowdnet/') if re.match(r'train-*', f)]

['/Users/vladyslav.shkola/MasterThesis/crowdnet/implementation/crowdnet/train-00000-of-00002.tfrecords',
 '/Users/vladyslav.shkola/MasterThesis/crowdnet/implementation/crowdnet/train-00001-of-00002.tfrecords']

In [16]:
tf.python_io.tf_record_iterator('/Users/vladyslav.shkola/MasterThesis/crowdnet/implementation/crowdnet/train-00000-of-00002.tfrecords')

<generator object tf_record_iterator at 0x118242410>

In [14]:
import os

def absoluteFilePaths(directory):
   for dirpath,_,filenames in os.walk("crowdnet/"):
       for f in filenames:
           yield os.path.abspath(os.path.join(dirpath, f))

In [20]:
tfrecords_files = [os.path.abspath(os.path.join('crowdnet/', f)) for f in os.listdir('crowdnet/') if re.match(r'validation-*', f)]
c = 0
for fn in tfrecords_files:
    for _ in tf.python_io.tf_record_iterator(fn):
        c += 1
        
print("samples in total: {}".format(c))

samples in total: 47


In [6]:
import os
import tensorflow as tf

tfrecords_files = [os.path.abspath(os.path.join('crowdnet_test/', f)) for f in os.listdir('crowdnet_test/')]
c = 0
for fn in tfrecords_files:
    for _ in tf.python_io.tf_record_iterator(fn):
        c += 1
print("samples in total: {}".format(c))

samples in total: 20368


In [4]:
import tensorflow as tf
import os

filenames = tf.train.match_filenames_once(os.path.join("crowndet","train-*"))

filename_queue = tf.train.string_input_producer(filenames)

In [15]:
import tensorflow as tf

ds = tf.contrib.data

ImportError: cannot import name gen_checkpoint_ops